### ISSUE TITLE
1.12.2 Forge: SevTech Ages advancements crashes StringError("stream did not contain valid UTF-8") 

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#148]
SevTech_Ages_Server_3.1.1 (1.12.2, top 3 on Curseforge)

crashes on login:
packet = Some(PluginMessageClientbound(PluginMessageClientbound { channel: "thebetweenlands", data: [17, 0, 0, 0, 18, 0, 0, 0, 16, 10, 0, 0, 0] }))
Decompressed threshold=256 len=2352 uncompressed_size=14939 to 14939 bytes
about to parse id=4d, dir=Clientbound state=Play
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 14, 0, 0, 0, 11, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 16, 0, 0, 0, 12, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 15, 0, 0, 0, 20, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 17, 0, 0, 0, 13, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 8, 0, 0, 0, 16, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 8, 0, 0, 0, 15, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 11, 0, 0, 0, 11, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 8, 0, 0, 0, 17, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 15, 0, 0, 0, 11, 10, 0, 0, 0]
Received plugin message: channel=thebetweenlands, data=[17, 0, 0, 0, 18, 0, 0, 0, 16, 10, 0, 0, 0]
thread 'main' panicked at 'Err: IOError(Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") })', src/server/mod.rs:449:33

Found in #146 1.12.2/1.10.2 Forge: Beyond/Skyfactory3/SevTech Ages crashes: error: StringError("failed to fill whole buffer") / java.util.zip.DataFormatException: incorrect header check, which extends #144 Forge 1.8.9-1.12.2 handshake protocol support. 1.12.2 protocol: https://wiki.vg/index.php?title=Protocol&oldid=14204

Full backtrace:

```
thread 'main' panicked at 'Err: IOError(Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") })', src/server/mod.rs:449:33
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:340
   7: stevenarella::server::Server::entity_tick
             at src/server/mod.rs:449
   8: stevenarella::server::Server::tick
             at src/server/mod.rs:356
   9: stevenarella::main
             at src/main.rs:326
  10: std::rt::lang_start::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  13: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
```

**Comment by iceiix** [comment]
Packet 0x4d is Advancements: https://wiki.vg/index.php?title=Protocol&oldid=14204#Advancements

**Comment by iceiix** [comment]
Improved the generic "did not contain valid UTF-8" error in  https://github.com/iceiix/stevenarella/commit/10e5d6f44186c6acdf87666a6f00744d20744d0c, it's parsing a large number of bytes:

about to parse id=4d, dir=Clientbound state=Play
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [101, 116, 101, 100, 80, 97, 114, 101, 110, 116, 1, 7, 104, 97, 115, 82, 111, 99, 107, 21, 116, 114, 105, 117, 109, 112,...

decodes to 'etedParent\x01\x07hasRock\x15triumph:stage0/melter\x01\x19triumph:stage0...', which is at offset 211 in last_packet. Before is:

'M\x015\x12triumph:stage0/mat\x01\x16triumph:stage0/leather\x01-{"translate":"advancements.stage0.mat.title"}3{"translate":"advancements.stage0.mat.description"}%\x05\x01\x00\x00\x00\x00\x00\x00\x00\n@\xe0\x00\x00A%\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x0fcompl

supposed to be the string length-prefixed "\x0fcompletedParent". Advancements is new in 1.12.2 (not present in 1.11.2). 

manually decoding:
M - 0x4d
\x01 - reset/clear bool
5 - 0x35 = 53, mapping size
\x12triumph:stage0/mat - identifier
\x01 - has parent
\x16triumph:stage0/leather
\x01 - has display
0x2d (-) = 45
 {"translate":"advancements.stage0.mat.title"} = display
0x33 (3) = 51
{"translate":"advancements.stage0.mat.description"}
%\x05\x01\x00\x00\x00\x00\x00\x00\x00\n@\xe0\x00\x00A%\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02
\x0fcompletedParent
\x07hasRock

adding lots of logging:

```diff
diff --git a/src/protocol/packet.rs b/src/protocol/packet.rs
index 6fb57e9..d35b214 100644
--- a/src/protocol/packet.rs
+++ b/src/protocol/packet.rs
@@ -2046,18 +2046,24 @@ pub struct Advancement {
 
 impl Serializable for Advancement {
     fn read_from<R: io::Read>(buf: &mut R) -> Result<Self, Error> {
+        println!("reading Advancement");
         let id: String = Serializable::read_from(buf)?;
+        println!("id={}", id);
         let parent_id = {
             let has_parent: u8 = Serializable::read_from(buf)?;
+            println!("has_parent? {}", has_parent);
             if has_parent != 0 {
                 let parent_id: String = Serializable::read_from(buf)?;
+                println!("parent_id {}",parent_id);
                 Some(parent_id)
             } else {
                 None
             }
         };
+        println!("parent_id={:?}", parent_id);
 
         let has_display: u8 = Serializable::read_from(buf)?;
+        println!("has_display {}", has_display);
         let display_data = {
             if has_display != 0 {
                 let display_data: AdvancementDisplay = Serializable::read_from(buf)?;
@@ -2066,9 +2072,12 @@ impl Serializable for Advancement {
                 None
             }
         };
+        println!("display_data {:?}", display_data);
 
         let criteria: LenPrefixed<VarInt, String> = Serializable::read_from(buf)?;
+        println!("criteria {:?}", criteria);
         let requirements: LenPrefixed<VarInt, LenPrefixed<VarInt, String>> = Serializable::read_from(buf)?;
+        println!("requirements {:?}", requirements);
         Ok(Advancement {
             id,
             parent_id,
@@ -2102,18 +2111,27 @@ pub struct AdvancementDisplay {
 
 impl Serializable for AdvancementDisplay {
     fn read_from<R: io::Read>(buf: &mut R) -> Result<Self, Error> {
+        println!("reading AdvancementDisplay");
         let title: String = Serializable::read_from(buf)?;
+        println!("title {}", title);
         let description: String = Serializable::read_from(buf)?;
+        println!("description {}", description);
         let icon: Option<crate::item::Stack> = Serializable::read_from(buf)?;
+        println!("icon {:?}", icon);
         let frame_type: VarInt = Serializable::read_from(buf)?;
+        println!("frame_type {:?}", frame_type);
         let flags: i32 = Serializable::read_from(buf)?;
+        println!("flags {}", flags);
         let background_texture: Option<String> = if flags & 1 != 0 {
             Serializable::read_from(buf)?
         } else {
             None
         };
+        println!("background_texture {:?}", background_texture);
         let x_coord: f32 = Serializable::read_from(buf)?;
+        println!("x_coord {:?}", x_coord);
         let y_coord: f32 = Serializable::read_from(buf)?;
+        println!("y_coord {:?}", y_coord);
 
         Ok(AdvancementDisplay {
             title,
@@ -2170,13 +2188,17 @@ pub struct CriterionProgress {
 
 impl Serializable for CriterionProgress {
     fn read_from<R: io::Read>(buf: &mut R) -> Result<Self, Error> {
+        println!("read CriterionProgress");
         let id = Serializable::read_from(buf)?;
+        println!("id {:?}", id);
         let achieved: u8 = Serializable::read_from(buf)?;
+        println!("achieved {:?}", achieved);
         let date_of_achieving: Option<i64> = if achieved != 0 {
             Serializable::read_from(buf)?
         } else {
             None
         };
+        println!("date {:?}", date_of_achieving);
 
         Ok(CriterionProgress {
             id,
```

output:

about to parse id=18, dir=Clientbound state=Play
packet = Some(PluginMessageClientbound(PluginMessageClientbound { channel: "thebetweenlands", data: [17, 0, 0, 0, 12, 0, 0, 0, 26, 10, 0, 0, 0] }))
Decompressed threshold=256 len=2360 uncompressed_size=14986 to 14986 bytes
about to parse id=4d, dir=Clientbound state=Play
reading Advancement
id=triumph:stage0/mat
has_parent? 1
parent_id triumph:stage0/leather
parent_id=Some("triumph:stage0/leather")
has_display 1
reading AdvancementDisplay
title {"translate":"advancements.stage0.mat.title"}
description {"translate":"advancements.stage0.mat.description"}
icon Some(Stack { id: 9477, count: 1, damage: Some(0), tag: None })
frame_type 0
flags 10
background_texture None
x_coord 7.0
y_coord 10.3125
display_data Some(AdvancementDisplay { title: "{\"translate\":\"advancements.stage0.mat.title\"}", description: "{\"translate\":\"advancements.stage0.mat.description\"}", icon: Some(Stack { id: 9477, count: 1, damage: Some(0), tag: None }), frame_type: 0, flags: 10, background_texture: None, x_coord: 7.0, y_coord: 10.3125 })
criteria []
requirements []
reading Advancement
id=
has_parent? 0
parent_id=None
has_display 0
display_data None
criteria []
requirements []
reading Advancement
id=
has_parent? 0
parent_id=None
has_display 0
display_data None
criteria []
requirements []
reading Advancement
id=
has_parent? 0
parent_id=None
has_display 2
reading AdvancementDisplay
title completedParent
description hasRock
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [101, 116, 101, 100, 80,

**Comment by iceiix** [comment]
This Forge change looks suspect: https://github.com/MinecraftForge/MinecraftForge/pull/4114 Allow advancement icons to have nbt, but the discussion claims standard deserialization will read/write it:

> the stack is just written and read wholesale using PacketBuffer.readItemStack/writeItemStack, the json deserialization just ignores it for some reason

and indeed the icon is an `Option<crate::item::Stack>`.

There is support in Forge for loading mod enhancements: https://github.com/MinecraftForge/MinecraftForge/commit/a4fb33d9459ac73831baec908f18d8f19f3cd6c0 Add support for loading mod advancements from the mod jar files.

And another change to support oredict item predicates in advancements: https://github.com/MinecraftForge/MinecraftForge/pull/4188 Add support for oredict item predicates in advancements, and add a registry for item predicates - it changes the critereon[sic] criterion, but maybe not the packet? But there is also added resilience in Forge, an option to continue on errors: https://github.com/MinecraftForge/MinecraftForge/pull/4277 [1.12] Continue loading mod recipes and advancements after encountering an error . 

A big change is allowing pagination on advancements: https://github.com/MinecraftForge/MinecraftForge/pull/4183 - client-side only apparently. Finally, another robustness change: https://github.com/MinecraftForge/MinecraftForge/commit/6d35b1b913c1a8116743418efdf63d33de048e7a Fixed invalid erroring case during loading Advancements form mods that don't have advancements.

Worst case, could just ignore the Advancements packet, avoiding parsing it, skipping over the byte length... this would allow connecting, and the packets aren't supported anyways yet here.

**Comment by iceiix** [comment]
[last-packet.zip](https://github.com/iceiix/stevenarella/files/3170619/last-packet.zip)

**Comment by iceiix** [comment]
Filed to node-minecraft-protocol since they also can't parse this packet, if they are interested in adding support too: https://github.com/PrismarineJS/node-minecraft-protocol/issues/627

but for now, may be the most expedient to just skip parsing this packet: https://github.com/iceiix/stevenarella/pull/149. It is a big hairy packet, could cause a lot of problems and I'm not even using it...
