### ISSUE TITLE
World won't load: FromUtf8Error { bytes: [255, 255, 183, 63, 255, 253, 224, 87, 3], error: Utf8Error 

### ISSUE THREAD

**Issue by 715209** [iceiix/stevenarella#212]
When i join a server nothing loads but i can see myself.

![image](https://user-images.githubusercontent.com/5977687/63097166-06a17e00-bf70-11e9-9789-495432b4fba5.png)

Also getting this error:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [255, 255, 183, 63, 255, 253, 224, 87, 3], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed
  11: <alloc::string::String as stevenarella::protocol::Serializable>::read_from
  12: stevenarella::protocol::packet::packet_by_id
  13: stevenarella::protocol::Conn::read_packet
```

Am I doing something wrong?

**Comment by iceiix** [comment]
UTF-8 string decode error, I've seen several of these when the protocol decode fails. Rust is very strict on invalid UTF-8, in this case it cannot decode '\xff\xff\xb7?\xff\xfd\xe0W\x03', but that doesn't appear to be a valid string anyway, so the problem is probably deeper.

@715209 Can you try rerunning with the --network-debug flag (e.g., `target/release/stevenarella --network-debug`) then attach the file `last-packet` and the end of the console log? Also what server are you connecting to, is it a public server, or if a private server do you know the game version?

**Comment by 715209** [comment]
It suddenly started working but the textures are wrong (except the stone)

![image](https://user-images.githubusercontent.com/5977687/63110599-1d55ce00-bf8c-11e9-9fe4-eb2722a7169e.png)

Still see the Utf8Error.

```
0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3], block_entities: [Some(NamedTag("", Compound({"x": Int(-294), "id": String("minecraft:bed"), "y": Int(92), "z": Int(-33)}))), Some(NamedTag("", Compound({"x": Int(-295), "y": Int(92), "z": Int(-33), "id": String("minecraft:bed")}))), Some(NamedTag("", Compound({"x": Int(-301), "y": Int(87), "z": Int(-34), "id": String("minecraft:chest")}))), Some(NamedTag("", Compound({"id": String("minecraft:chest"), "x": Int(-301), "z": Int(-35), "y": Int(87)}))), Some(NamedTag("", Compound({"z": Int(-33), "Text4": String("{\"text\":\"\"}"), "id": String("minecraft:sign"), "Text1": String("{\"text\":\"\"}"), "y": Int(85), "Color": String("black"), "Text2": String("{\"text\":\"x73x\'s\"}"), "Text3": String("{\"text\":\"Tower\"}"), "x": Int(-292)}))), Some(NamedTag("", Compound({"x": Int(-294), "z": Int(-33), "id": String("minecraft:jukebox"), "y": Int(88)})))] }))
[protocol/mod.rs:1073][DEBUG] about to parse id=4, dir=Clientbound state=Play
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [255, 255, 183, 63, 255, 253, 224, 87, 3], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed
  11: <alloc::string::String as stevenarella::protocol::Serializable>::read_from
  12: stevenarella::protocol::packet::packet_by_id
  13: stevenarella::protocol::Conn::read_packet
[model/mod.rs:194][ERROR] Error missing block state for minecraft:player_head
[model/mod.rs:173][ERROR] Error loading model minecraft:player_head
[model/mod.rs:194][ERROR] Error missing block state for minecraft:zombie_head
[model/mod.rs:173][ERROR] Error loading model minecraft:zombie_head
[model/mod.rs:194][ERROR] Error missing block state for minecraft:skull
[model/mod.rs:173][ERROR] Error loading model minecraft:skull
[model/mod.rs:194][ERROR] Error missing block state for minecraft:smooth_quartz
[model/mod.rs:173][ERROR] Error loading model minecraft:smooth_quartz
[model/mod.rs:194][ERROR] Error missing block state for minecraft:smooth_stone
[model/mod.rs:173][ERROR] Error loading model minecraft:smooth_stone
```
[last-packet.txt](https://github.com/iceiix/stevenarella/files/3506411/last-packet.txt)

**Comment by iceiix** [comment]
For the wrong textures on new blocks, started fixing this in https://github.com/iceiix/stevenarella/pull/71 but it is incomplete and there are some open compatibility questions for older game versions...

For UTF8 decode error, will have to investigate this more. At least the error is consistent:

bytes: [255, 255, 183, 63, 255, 253, 224, 87, 3]

this matches the bytes in your last-packet:

```
00000000  00 04 f1 04 37 d9 bb 69  35 17 4f 6f 8a 78 52 0a  |....7..i5.Oo.xR.|
00000010  2c 70 2f 49 12 ff ff b7  3f ff fd e0 57 03        |,p/I....?...W.|
```

ff ff b7 3f ff fd e0 57 03, very end of the packet.

Testing with this patch to reproduce:

```diff
diff --git a/src/main.rs b/src/main.rs
index 6269339..f9351f8 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -201,6 +201,8 @@ cfg_if! {
     }
 }
 
+use std::fs;
+use std::io::Read;
 fn main2() {
     let opt = Opt::from_args();
 
@@ -215,6 +217,15 @@ fn main2() {
 
     info!("Starting steven");
 
+    println!("open");
+    let mut file = fs::File::open("last-packet").unwrap();
+    //let mut buf = vec![];
+    //file.read_to_end(&mut buf).unwrap();
+    println!("about to parse");
+    let packet = crate::protocol::packet::packet_by_id(498, crate::protocol::State::Play, crate::protocol::Direction::Clientbound, 0x04, &mut file);
+    println!("packet = {:?}", packet);
+    return;
+
     let (vars, vsync) = {
         let mut vars = console::Vars::new();
         vars.register(CL_BRAND);
```

and last-packet copied except first two bytes. 

I can replicate the error. Looks like this is packet 0x04 = SpawnPainting https://wiki.vg/Protocol#Client_Status but I have the wrong fields,

```rust
            packet SpawnPainting {
                field entity_id: VarInt =,
                field uuid: UUID =,
                field title: String =,
                field location: Position =,
                field direction: u8 =,
            }
```

no `title: String` in recent protocols, should be `motive: VarInt`.

**Comment by iceiix** [comment]
@715209 Pushed a fix, can you try latest? (as of https://github.com/iceiix/stevenarella/commit/d24b6cb599605b3b80f74fc409852191e8bee9ec) There was a packet I must have missed updating as part of https://github.com/iceiix/steven/pull/67, so I fixed the definition, it parses now in my testing (though there could be other broken packets, on a real server, which I'd also be interested in if you run into them)

**Comment by 715209** [comment]
Looks like it works 👍 

![image](https://user-images.githubusercontent.com/5977687/63217381-fd6a0a00-c145-11e9-80fb-b510588fedd5.png)
