### ISSUE TITLE
Linux: Starting under Wayland

### ISSUE THREAD

**Issue by mwkroening** [iceiix/stevenarella#316]
Currently, sevenarella does not work when run under Wayland.

The first problem of not being able to start seems to be within winit. Upgrading solves this issue. I'll come up with a PR similar to #268.

<details>
 <summary>Terminal output</summary>

```
$ RUST_BACKTRACE=full cargo run --release
warning: file found to be present in multiple build targets: /home/mkroening/Development/stevenarella/src/main.rs
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/stevenarella`
[main.rs:216][INFO] Starting steven
[blocking/wait.rs:46][TRACE] (ThreadId(2)) park without timeout
[poll.rs:787][TRACE] registering with poller
[poll.rs:787][TRACE] registering with poller
[poll.rs:787][TRACE] registering with poller
[poll.rs:787][TRACE] registering with poller
[blocking/client.rs:653][TRACE] (ThreadId(3)) start runtime::block_on
[poll.rs:787][TRACE] registering with poller
[poll.rs:787][TRACE] registering with poller
[poll.rs:787][TRACE] registering with poller
[blocking/wait.rs:46][TRACE] (ThreadId(4)) park without timeout
[poll.rs:787][TRACE] registering with poller
[blocking/client.rs:653][TRACE] (ThreadId(5)) start runtime::block_on
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/mkroening/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha6/src/platform_impl/linux/wayland/window.rs:341:22
stack backtrace:
[blocking/client.rs:600][TRACE] closing runtime thread (ThreadId(3))
[blocking/client.rs:602][TRACE] signaled close for runtime thread (ThreadId(3))
[blocking/client.rs:650][TRACE] (ThreadId(3)) Receiver is shutdown
[blocking/client.rs:655][TRACE] (ThreadId(3)) end runtime::block_on
[blocking/client.rs:657][TRACE] (ThreadId(3)) finished
[blocking/client.rs:604][TRACE] closed runtime thread (ThreadId(3))
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: winit::platform_impl::platform::wayland::window::Window::current_monitor
  15: stevenarella::main2
  16: stevenarella::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[blocking/client.rs:600][TRACE] closing runtime thread (ThreadId(5))
[blocking/client.rs:602][TRACE] signaled close for runtime thread (ThreadId(5))
[blocking/client.rs:650][TRACE] (ThreadId(5)) Receiver is shutdown
[blocking/client.rs:655][TRACE] (ThreadId(5)) end runtime::block_on
[blocking/client.rs:657][TRACE] (ThreadId(5)) finished
[blocking/client.rs:604][TRACE] closed runtime thread (ThreadId(5))
```
</details>

**Comment by mwkroening** [comment]
This issue is caused by the fact that we try to get the monitor of the main window before it is visible and thus has no monitor on Wayland.

See https://github.com/rust-windowing/winit/issues/793

**Comment by mwkroening** [comment]
There are more issues on Wayland but I will tackle those seperately.
