### ISSUE TITLE
Fails parsing 1.12.2 chunk info

### ISSUE THREAD

**Issue by cookiedragon234** [iceiix/stevenarella#393]
When entering the nether on a 1.12.2 server the following crash occurs:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', protocol/src/types/bit/map.rs:99:15
stack backtrace:
 14: <usize as core::slice::SliceIndex<[T]>>::index
             at /home/cook/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:3103
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /home/cook/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2955
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /home/cook/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1975
  17: steven_protocol::types::bit::map::Map::get
             at protocol/src/types/bit/map.rs:99
  18: stevenarella::world::World::load_chunk19_or_115
             at src/world/mod.rs:1072
  19: stevenarella::world::World::load_chunk19
             at src/world/mod.rs:989
  20: stevenarella::server::Server::on_chunk_data
             at src/server/mod.rs:1813
  21: stevenarella::server::Server::entity_tick
             at src/server/mod.rs:508
  22: stevenarella::server::Server::tick
             at src/server/mod.rs:463
  23: stevenarella::main2::{{closure}}
             at src/main.rs:374
```
Probably not directly caused by the nether but some unexpected edge case in chunk loading. I would fix this myself, but after looking at the chunk format section at wiki.vg I am permanently scarred.

**Comment by iceiix** [comment]
"index out of bounds: the len is 0 but the index is 0", so the array is empty for some reason - will need to try to repro
