### ISSUE TITLE
crash in load_block_entities block_entity.1.get("id") at src/server/mod.rs:1773 thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by mcfd** [iceiix/stevenarella#445]
```
[blocking/wait.rs:17][TRACE] wait at most 30s
[blocking/wait.rs:43][TRACE] (ThreadId(4)) park timeout 29.999995119s
[client/pool.rs:614][TRACE] checkout waiting for idle connection: ("http", textures.minecraft.net)
[connect.rs:526][DEBUG] starting new connection: http://textures.minecraft.net/
[client/connect/http.rs:279][TRACE] Http::connect; scheme=Some("http"), host=Some("textures.minecraft.net"), port=None
[client/connect/dns.rs:121][DEBUG] resolving host="textures.minecraft.net"
[client/connect/http.rs:560][DEBUG] connecting to 13.225.146.2:80
[poll.rs:787][TRACE] registering with poller
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/server/mod.rs:1773:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: stevenarella::server::Server::load_block_entities
   4: stevenarella::server::Server::entity_tick
   5: stevenarella::server::Server::tick
   6: stevenarella::main2::{{closure}}
   7: winit::platform_impl::platform::x11::EventLoop<T>::run
   8: winit::platform_impl::platform::EventLoop<T>::run
   9: winit::event_loop::EventLoop<T>::run
  10: stevenarella::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[client/connect/http.rs:571][DEBUG] connected to 13.225.146.2:80
[client/conn.rs:607][TRACE] client handshake HTTP/1
[client/mod.rs:514][TRACE] handshake complete, spawning background dispatcher task
[lib.rs:341][TRACE] signal: Want
[lib.rs:355][TRACE] signal found waiting giver, notifying
[proto/h1/conn.rs:650][TRACE] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[lib.rs:200][TRACE] poll_want: taker wants!
[client/pool.rs:656][TRACE] checkout dropped for ("http", textures.minecraft.net)
[proto/h1/role.rs:88][TRACE] encode_headers
[proto/h1/role.rs:88][TRACE] -> encode_headers
[proto/h1/role.rs:730][TRACE] Client::encode method=GET, body=None
[proto/h1/role.rs:88][TRACE] <- encode_headers
[proto/h1/role.rs:88][TRACE] -- encode_headers
[proto/h1/io.rs:595][TRACE] detected no usage of vectored write, flattening
[proto/h1/io.rs:229][DEBUG] flushed 131 bytes
[proto/h1/conn.rs:650][TRACE] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
```

**Comment by mcfd** [comment]
server:mc.kinomc.cn

**Comment by iceiix** [comment]
thread 'main' panicked at 'called Option::unwrap() on a None value', src/server/mod.rs:1773:56

```rust
    fn load_block_entities(&mut self, block_entities: Vec<Option<crate::nbt::NamedTag>>) {
        for optional_block_entity in block_entities {
            if let Some(block_entity) = optional_block_entity {
                let x = block_entity.1.get("x").unwrap().as_int().unwrap();
                let y = block_entity.1.get("y").unwrap().as_int().unwrap();
                let z = block_entity.1.get("z").unwrap().as_int().unwrap();
                let tile_id = block_entity.1.get("id").unwrap().as_str().unwrap(); // crash here

```

Interesting, a block entity with xyz coordinates but no "id". According to https://minecraft.gamepedia.com/Chunk_format#Block_entity_format the x,y,z,id fields should be common to all block entities. Maybe it changed, or maybe this block entity is corrupted on the server, or some other error... I suppose we could more gracefully handle this "missing id" condition. Another possibility: nbt as_str failing (returns `Option<&[Tag]>`), not a `Tag::String` id, but some other type? (or string conversion failed, non-UTF8?)

**Comment by iceiix** [comment]
Added a check in https://github.com/iceiix/stevenarella/commit/71121bd5722c56992f610023841a4d811815b835 to check for and log a warning when block entities are found without "id" (instead of crashing)
