### ISSUE TITLE
1.16.4: panic unsupported command node parser minecraft:angle, protocol/src/protocol/packet.rs:3265:22

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#466]
Observed when connecting to a 1.16.4 server:

```
thread '<unnamed>' panicked at 'unsupported command node parser minecraft:angle', protocol/src/protocol/packet.rs:3265:22
```

https://minecraft.gamepedia.com/Argument_types#angle

**Comment by iceiix** [comment]
After handling minecraft:angle (the only argument type missing), another panic:

```
thread '<unnamed>' panicked at 'unrecognized command node type 3', protocol/src/protocol/packet.rs:3151:18
```

here:

```rust
impl Serializable for CommandNode {
    fn read_from<R: io::Read>(buf: &mut R) -> Result<Self, Error> {
        let flags: u8 = Serializable::read_from(buf)?;
        let children: LenPrefixed<VarInt, VarInt> = Serializable::read_from(buf)?;

        let node_type = match flags & 0x03 {
            0 => CommandNodeType::Root,
            1 => CommandNodeType::Literal,
            2 => CommandNodeType::Argument,
            _ => panic!("unrecognized command node type {}", flags & 0x03),
        };
```

https://wiki.vg/Command_Data
