### ISSUE TITLE
Client crashing when connecting to servers.

### ISSUE THREAD

**Issue by fenrave** [iceiix/stevenarella#613]
```
[main.rs:254][INFO] Starting steven
[platform_impl/linux/x11/window.rs:140][INFO] Guessed window scale factor: 1
[main.rs:346][INFO] Shader version: #version 150
[main.rs:99][INFO] Detected server protocol version 756
[server/mod.rs:1916][INFO] Received chat message:                                      
thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x59, had 11 bytes left")', src/server/mod.rs:652:33
stack backtrace:
   0:     0x555cfafcbab0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x555cfafcbab0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555cfafcbab0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555cfafcbab0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x555cfafefbcc - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x555cfafc4bd5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x555cfafcdbeb - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x555cfafcdbeb - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x555cfafcdbeb - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x555cfafcd6c1 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x555cfafce2b4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x555cfafcdd97 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x555cfafcbfac - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x555cfafcdcf9 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x555cfa84543b - std::panicking::begin_panic_fmt::h5479575e112541f8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
  15:     0x555cfa97e802 - stevenarella::server::Server::entity_tick::h45067817db77013a
  16:     0x555cfa976170 - stevenarella::server::Server::tick::h2426ba163ae4161e
  17:     0x555cfa934ba2 - stevenarella::tick_all::hcefc405af0517984
  18:     0x555cfa8f6550 - stevenarella::main2::{{closure}}::hb549fc64d957b74e
  19:     0x555cfa91ea51 - winit::platform_impl::platform::x11::EventLoop<T>::run::hfda87fd8f73cd1fa
  20:     0x555cfa8dd4d0 - winit::platform_impl::platform::EventLoop<T>::run::he4474d8a08321bc9
  21:     0x555cfa91e73c - winit::event_loop::EventLoop<T>::run::h81a655f4f36680ed
  22:     0x555cfa9334c3 - stevenarella::main2::h69ea0e365eaa92ca
  23:     0x555cfa938373 - std::sys_common::backtrace::__rust_begin_short_backtrace::h086b9c72e137761f
  24:     0x555cfa9adc49 - std::rt::lang_start::{{closure}}::h6c480b78ef968e46
  25:     0x555cfafce8b9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  26:     0x555cfafce8b9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  27:     0x555cfafce8b9 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  28:     0x555cfafce8b9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  29:     0x555cfafce8b9 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  30:     0x555cfa9363c2 - main
  31:     0x7ff279cedb75 - __libc_start_main
  32:     0x555cfa8468ae - _start
  33:                0x0 - <unknown>

```

Tried to connect to mc.hypixel.net, client crashes immediately. 

I also tried a 1.16.5 server to see if it was just the 756 protocol having issues.

```
[main.rs:254][INFO] Starting steven
[platform_impl/linux/x11/window.rs:140][INFO] Guessed window scale factor: 1
[main.rs:346][INFO] Shader version: #version 150
[main.rs:99][INFO] Detected server protocol version 756
[server/mod.rs:1916][INFO] Received chat message: -------- Welcome to MANACUBE --------
[server/mod.rs:1916][INFO] Received chat message:  
[server/mod.rs:1916][INFO] Received chat message:        Watch our NEW Official Trailer
[server/mod.rs:1916][INFO] Received chat message:        https://youtu.be/YpNGlgZn2u4
[server/mod.rs:1916][INFO] Received chat message: 
[server/mod.rs:1916][INFO] Received chat message: ------------------------------------
[server/mod.rs:1916][INFO] Received chat message: You have no new mail.
thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x27, had 16387 bytes left")', src/server/mod.rs:652:33
stack backtrace:
   0:     0x55d651362ab0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d651362ab0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d651362ab0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d651362ab0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d651386bcc - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55d65135bbd5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55d651364beb - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d651364beb - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d651364beb - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55d6513646c1 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55d6513652b4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55d651364d97 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x55d651362fac - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d651364cf9 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55d650bdc43b - std::panicking::begin_panic_fmt::h5479575e112541f8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
  15:     0x55d650d15802 - stevenarella::server::Server::entity_tick::h45067817db77013a
  16:     0x55d650d0d170 - stevenarella::server::Server::tick::h2426ba163ae4161e
  17:     0x55d650ccbba2 - stevenarella::tick_all::hcefc405af0517984
  18:     0x55d650c8d550 - stevenarella::main2::{{closure}}::hb549fc64d957b74e
  19:     0x55d650cb5a51 - winit::platform_impl::platform::x11::EventLoop<T>::run::hfda87fd8f73cd1fa
  20:     0x55d650c744d0 - winit::platform_impl::platform::EventLoop<T>::run::he4474d8a08321bc9
  21:     0x55d650cb573c - winit::event_loop::EventLoop<T>::run::h81a655f4f36680ed
  22:     0x55d650cca4c3 - stevenarella::main2::h69ea0e365eaa92ca
  23:     0x55d650ccf373 - std::sys_common::backtrace::__rust_begin_short_backtrace::h086b9c72e137761f
  24:     0x55d650d44c49 - std::rt::lang_start::{{closure}}::h6c480b78ef968e46
  25:     0x55d6513658b9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  26:     0x55d6513658b9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  27:     0x55d6513658b9 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  28:     0x55d6513658b9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  29:     0x55d6513658b9 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  30:     0x55d650ccd3c2 - main
  31:     0x7fb18436ab75 - __libc_start_main
  32:     0x55d650bdd8ae - _start
  33:                0x0 - <unknown>

```

I am on xWayland, I don't know if that'll cause issues though.

**Comment by iceiix** [comment]
Both of these are detected as 1.17.1 servers (protocol version number 756), could be either a version detection error, or packet parsing error, or both - possibly multiple bugs here:

hypixel: Failed to read all of packet 0x59, had 11 bytes left
Title packet

manacube: Failed to read all of packet 0x27, had 16387 bytes left
UpdateCommandBlockMinecart packet

if a protocol version detection error, a workaround may be to pass -p to override the detected protocol -
