### ISSUE TITLE
build: fontconfig not found despite being present

### ISSUE THREAD

**Issue by CrimsonFork** [iceiix/stevenarella#721]
Can't think of much to add other than the title

<details><summary><code>backtrace</code></summary>

```
$ RUST_BACKTRACE=full cargo run --release
warning: file found to be present in multiple build targets: /media/b/Boris/data/software/git/stra/stevenarella/src/main.rs
   Compiling servo-fontconfig-sys v5.1.0
   Compiling rayon-core v1.9.3
   Compiling num-rational v0.4.1
   Compiling xcb v1.1.1
   Compiling glutin_glx_sys v0.1.8
   Compiling aes v0.7.5
   Compiling cfb8 v0.7.1
   Compiling wayland-client v0.29.4
   Compiling glutin_egl_sys v0.1.6
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`

Caused by:
  process didn't exit successfully: `/media/b/Boris/data/software/git/stra/stevenarella/target/release/build/servo-fontconfig-sys-3107398df4d07e11/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  error: could not find system library 'fontconfig' required by the 'servo-fontconfig-sys' crate

  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /home/b/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  stack backtrace:
     0:     0x55b55cb17adc - std::backtrace_rs::backtrace::libunwind::trace::h7919b8809318ac9c
                                 at /rustc/1.62.1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55b55cb17adc - std::backtrace_rs::backtrace::trace_unsynchronized::h979f463b12f9afbe
                                 at /rustc/1.62.1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55b55cb17adc - std::sys_common::backtrace::_print_fmt::ha65c80ea2d19761b
                                 at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x55b55cb17adc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::heb07c6f5e244b5c7
                                 at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x55b55cb3263e - core::fmt::write::hb9bf2ca75bb61ce8
                                 at /rustc/1.62.1/library/core/src/fmt/mod.rs:1196:17
     5:     0x55b55cafa971 - std::io::Write::write_fmt::h3d203d49f14a282c
                                 at /rustc/1.62.1/library/std/src/io/mod.rs:1654:15
     6:     0x55b55cafecb5 - std::sys_common::backtrace::_print::h35e5e12251628ca9
                                 at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x55b55cafecb5 - std::sys_common::backtrace::print::h9c5850e31f400c78
                                 at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x55b55cafecb5 - std::panicking::default_hook::{{closure}}::h76e781ca7cabe79a
                                 at /rustc/1.62.1/library/std/src/panicking.rs:295:22
     9:     0x55b55cafe93a - std::panicking::default_hook::h1280745b25d74829
                                 at /rustc/1.62.1/library/std/src/panicking.rs:314:9
    10:     0x55b55caff1bc - std::panicking::rust_panic_with_hook::h7c45234a2beda55d
                                 at /rustc/1.62.1/library/std/src/panicking.rs:698:17
    11:     0x55b55cb18707 - std::panicking::begin_panic_handler::{{closure}}::hc0e935ca2ac846dc
                                 at /rustc/1.62.1/library/std/src/panicking.rs:588:13
    12:     0x55b55cb17d74 - std::sys_common::backtrace::__rust_end_short_backtrace::ha9c942b46b1fcfef
                                 at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x55b55cafee82 - rust_begin_unwind
                                 at /rustc/1.62.1/library/std/src/panicking.rs:584:5
    14:     0x55b55cac87f3 - core::panicking::panic_fmt::had7bb9c3ca3b1ba1
                                 at /rustc/1.62.1/library/core/src/panicking.rs:142:14
    15:     0x55b55cac9fad - core::panicking::panic_display::he363693135d9aec9
    16:     0x55b55cac8c44 - build_script_build::main::h7d926b59a6e2e2ca
    17:     0x55b55cac9833 - core::ops::function::FnOnce::call_once::he0a500df71139a40
    18:     0x55b55cac96f9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94c1c08fcdee94cd
    19:     0x55b55cac9f29 - std::rt::lang_start::{{closure}}::h70ba39de8bee9bcd
    20:     0x55b55cafa301 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4ea91ecf9912a8da
                                 at /rustc/1.62.1/library/core/src/ops/function.rs:280:13
    21:     0x55b55cafa301 - std::panicking::try::do_call::h8d9fa7852232ed78
                                 at /rustc/1.62.1/library/std/src/panicking.rs:492:40
    22:     0x55b55cafa301 - std::panicking::try::hbbb0ab9bad2924f1
                                 at /rustc/1.62.1/library/std/src/panicking.rs:456:19
    23:     0x55b55cafa301 - std::panic::catch_unwind::h1dd759c1023d296e
                                 at /rustc/1.62.1/library/std/src/panic.rs:137:14
    24:     0x55b55cafa301 - std::rt::lang_start_internal::{{closure}}::hfcce94f354adc8a7
                                 at /rustc/1.62.1/library/std/src/rt.rs:128:48
    25:     0x55b55cafa301 - std::panicking::try::do_call::h14afa92a4e26c0ac
                                 at /rustc/1.62.1/library/std/src/panicking.rs:492:40
    26:     0x55b55cafa301 - std::panicking::try::hf13e6ae8b45dbb51
                                 at /rustc/1.62.1/library/std/src/panicking.rs:456:19
    27:     0x55b55cafa301 - std::panic::catch_unwind::h4ca967112e99b077
                                 at /rustc/1.62.1/library/std/src/panic.rs:137:14
    28:     0x55b55cafa301 - std::rt::lang_start_internal::h4ce1552e33d7757f
                                 at /rustc/1.62.1/library/std/src/rt.rs:128:20
    29:     0x55b55cac9f11 - std::rt::lang_start::hb5b570ed86d6b30e
    30:     0x55b55cac91e3 - main
    31:     0x7ff751506d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    32:     0x7ff751506e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    33:     0x55b55cac89a5 - _start
    34:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
$ sudo nala install fontconfig
fontconfig is already at the latest version 2.13.1-4.2ubuntu5
Nothing for Nala to do.
```

</details>

**Comment by Bond-009** [comment]
You need to install the dev package of `fontconfig` (most likely called `fontconfig-dev`)
