### ISSUE TITLE
Trying to join an offline server fails "unhandled: multiplayer.player.joined"

### ISSUE THREAD

**Issue by CrimsonFork** [iceiix/stevenarella#723]
<details><summary><code>backtrace</code></summary>

```
$ RUST_BACKTRACE=full ./stevenarella -s 10.42.0.1 -u Hehebrine
[main.rs:254][INFO] Starting steven
[main.rs:346][INFO] Shader version: #version 150
[main.rs:99][INFO] Detected server protocol version 758
[server/mod.rs:176][WARN] Server is running in offline mode
[world/mod.rs:1012][INFO] Dimension type: {"logical_height": Int(384), "ultrawarm": Byte(0), "coordinate_scale": Double(1.0), "effects": String("minecraft:overworld"), "ambient_light": Float(0.0), "respawn_anchor_works": Byte(0), "height": Int(384), "infiniburn": String("#minecraft:infiniburn_overworld"), "natural": Byte(1), "min_y": Int(-64), "has_ceiling": Byte(0), "bed_works": Byte(1), "has_raids": Byte(1), "has_skylight": Byte(1), "piglin_safe": Byte(0)}
[server/mod.rs:1939][INFO] Received chat message: unhandled: multiplayer.player.joined
thread 'main' panicked at 'TODO: support chunk data y<0 non-air (bit_size 4, single_value Some(9), block_count 16)', src/world/mod.rs:1055:25
stack backtrace:
   0:     0x5648beeee6bc - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5648beeee6bc - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5648beeee6bc - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5648beeee6bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5648bef150cc - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5648beee6863 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x5648beef1032 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5648beef1032 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5648beef1032 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x5648beef0c15 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x5648beef1683 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x5648beef13a0 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x5648beeeeb64 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5648beef10d9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x5648be73f5f1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x5648be76346e - stevenarella::world::World::load_chunk19_to_117::h073e14d04070d2fc
  16:     0x5648be8b4bbc - stevenarella::server::Server::entity_tick::h64bf394d2d08e2fe
  17:     0x5648be8b1891 - stevenarella::server::Server::tick::hc55dd3b45c8cf5bd
  18:     0x5648be867ef6 - stevenarella::tick_all::hd5ed15eea7c9d4d0
  19:     0x5648be7fac0b - stevenarella::main2::{{closure}}::ha75139a7104857a9
  20:     0x5648be8362b4 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h5b9ea9a188976b17
  21:     0x5648be7fb6d0 - winit::platform_impl::platform::EventLoop<T>::run::hf45c3d10502e9ed2
  22:     0x5648be85f77a - winit::event_loop::EventLoop<T>::run::h135353eee356518d
  23:     0x5648be86699d - stevenarella::main2::h783623e936e02f58
  24:     0x5648be806683 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbda36a565946fd3c
  25:     0x5648be7652a9 - std::rt::lang_start::{{closure}}::ha80c958ce3d3f3fc
  26:     0x5648beeedd70 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  27:     0x5648beeedd70 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  28:     0x5648beeedd70 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  29:     0x5648beeedd70 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  30:     0x5648beeedd70 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  31:     0x5648beeedd70 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  32:     0x5648beeedd70 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  33:     0x5648beeedd70 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  34:     0x5648beeedd70 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  35:     0x5648be86c5d2 - main
  36:     0x7f4512b6cd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  37:     0x7f4512b6ce40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  38:     0x5648be73fd6e - _start
  39:                0x0 - <unknown>
```

**Comment by nathanruiz** [comment]
At the moment, negative chunks with non-air blocks aren't supported. I've put up a PR to fix it (#727). Until this is fixed, your best bet is using a pre 1.18 server.
